name: exercise one
on: [push, pull_request]
jobs:
  dependencies-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv --python 3.9
          pipenv install nose pylint --dev
      - name: Run test with nose
        run: |
          pipenv run nosetests
      - name: Run linter
        run: |
          pipenv run pylint app
  review:
    if: ${{ github.ref != 'refs/heads/master'}}
    needs: dependencies-run-tests
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
        title: Awesome PR by $GITHUB_ACTOR