name: exercise1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip     
        pip install pipenv
        pipenv --python 3.9
        pipenv install nose pylint --dev
    - name: Run test
      run: |
        pipenv run nosetests
      - name: Run lint
        run: |
          pipenv run pylint app


